language: julia
os:
  - linux
  - osx
julia:
  - 1.2
  - 1.3
  - nightly

notifications:
  email: false
sudo: false

after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("Clouds")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("Clouds")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
